[tool.autopep8]
max_line_length = 120

[tool.isort]
line_length = 120
multi_line_output = 0

[tool.ruff]
preview = true
lint.ignore = [
    "C416", "C901",
    "DJ008",
    "EM101", "EM102",
    "ERA001",
    "FURB140",
    "G004",
    "I001",
    "N801", "N802", "N803", "N806", 
    "N812", "N815", "N816", "N999", 
    "PD901",
    "PLR0912", "PLR0913", "PLR0914", "PLR0915", "PLR0917",
    "PLR2004", "PLW2901",
    "Q000",
    "S101",
    "SIM108", "SIM117",
    "SLF001",
    "T201",  # print statements
    "PLR0124",
]
lint.extend-select = [
    "F",
    "E", "W",
    "C90",
    "I",
    "N",
    # "D",
    "UP",
    "YTT",
    # "ANN",
    "ASYNC",
    "TRIO",
    "S",
    "BLE",
    "FBT",
    "B",
    "A",
    "COM",
    "C4",
    "DTZ", 
    "T10",
    "DJ",
    "EM",
    "EXE",
    # "FA",
    "ISC",
    "ICN",
    "G",
    "INP", 
    "PIE",
    "T20",
    "PYI",
    "PT",
    "Q",
    "RSE",
    "RET",
    "SLF",
    "SLOT",
    "SIM",
    "TID",
    "TCH",
    "INT",
    "ARG",
    # "PTH",
    "TD",
    "ERA",
    "PD",
    "PGH",
    "PL",
    # "TRY",
    "FLY",
    "NPY",
    "AIR",
    "PERF",
    "LOG",
    "RUF",

    # "CPY",
    "FURB",
    "C",
]
line-length = 120
cache-dir = "/tmp"
exclude = [
    "migrations",
    "D_*.py",
    "__init__.py",
]
target-version = "py39"

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"

[tool.ruff.lint.per-file-ignores]
"test_*.py" = ["S1", "FBT", "PLR"]

